knative-extensions/net-istio

CONTRIBUTING.md
DEVELOPMENT.md

Produced via:
`prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github)`
/cc tcnghia

Format markdown

---

Gopkg.lock
cmd/webhook/main.go
config/500-webhook.yaml
config/webhook-service.yaml
pkg/defaults/deployment_defaults.go
third_party/VENDOR-LICENSE
vendor/github.com/gobuffalo/envy/LICENSE
vendor/github.com/gobuffalo/envy/LICENSE.txt
vendor/github.com/gobuffalo/envy/envy.go
vendor/github.com/gobuffalo/envy/version.go
vendor/github.com/joho/godotenv/LICENCE
vendor/github.com/joho/godotenv/godotenv.go
vendor/github.com/markbates/inflect/LICENCE
vendor/github.com/markbates/inflect/helpers.go
vendor/github.com/markbates/inflect/inflect.go
vendor/github.com/markbates/inflect/name.go
vendor/github.com/markbates/inflect/version.go
vendor/github.com/rogpeppe/go-internal/LICENSE
vendor/github.com/rogpeppe/go-internal/modfile/gopkgin.go
vendor/github.com/rogpeppe/go-internal/modfile/print.go
vendor/github.com/rogpeppe/go-internal/modfile/read.go
vendor/github.com/rogpeppe/go-internal/modfile/rule.go
vendor/github.com/rogpeppe/go-internal/module/module.go
vendor/github.com/rogpeppe/go-internal/semver/semver.go

Fix #18 
This updates revisions on create:
```yaml
apiVersion: serving.knative.dev/v1
kind: Revision
labels:
service.istio.io/canonical-revision: helloworld-go-d4jk8
service.istio.io/canonical-service: helloworld-go
serving.knative.dev/configuration: helloworld-go
serving.knative.dev/configurationGeneration: "1"
serving.knative.dev/route: helloworld-go
serving.knative.dev/service: helloworld-go
name: helloworld-go-d4jk8
```

Add istio defaulting webhook

---

Gopkg.lock
vendor/knative.dev/serving/pkg/network/status/status.go

Produced via:
`./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/cc tcnghia

Auto-update dependencies

---

pkg/reconciler/ingress/resources/virtual_service.go
pkg/reconciler/ingress/resources/virtual_service_test.go

Closes: #44 
Related to: https://github.com/knative/serving/issues/7233
* **Description**
The gateways field of the VirtualService CRD indicates to which Istio
Gateways this VirtualService applies to.
At the moment, all configured gateways of are added to the gateways fields.
However, if the user wants to only specify a local gateway, they also
get the public gateway in that field.
This confuses the reconciler, which can't find the gateway and errors
out.
The VirtualService generation logic should instead only add gateways
which are used.
The new logic for adding a Gateway is:
Add all the Gateways that exist inside the http.match section of
the VirtualService.
This ensures that we are only using the Gateways that actually appear
in VirtualService routes.
@tcnghia at the moment, both …

Fix VirtualService generation: gateways field

---

pkg/reconciler/ingress/controller.go
pkg/reconciler/ingress/ingress.go

Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -path './third_party' -prune -o -type f -name '*.go' -print)`
`goimports -w $(find -name '*.go' | grep -v vendor | grep -v third_party)`
/cc tcnghia

[master] golang format tools

---

pkg/reconciler/ingress/resources/secret.go
pkg/reconciler/ingress/resources/secret_test.go

This is the first part for fixing https://github.com/knative/serving/issues/7495

Add helper functions for handling wildcard certificate

---

pkg/reconciler/ingress/ingress.go

- no need to log ingress name, it's attached to the context logger already
- backticks to stop escaping quotes
- other minor things
/assign @tcnghia @ZhiminXiang

Fix some logging around istio ingress

---

go.mod
go.sum
third_party/VENDOR-LICENSE
vendor/knative.dev/pkg/injection/context.go
vendor/knative.dev/pkg/injection/sharedmain/main.go
vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
vendor/knative.dev/pkg/network/prober/prober.go
vendor/knative.dev/pkg/test/helpers/dir.go
vendor/knative.dev/pkg/test/monitoring/monitoring.go
vendor/knative.dev/pkg/test/spoof/spoof.go
vendor/knative.dev/pkg/test/zipkin/util.go
vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
vendor/knative.dev/pkg/webhook/webhook.go
vendor/knative.dev/serving/pkg/resources/endpoints.go
vendor/knative.dev/serving/pkg/resources/pods.go
vendor/knative.dev/test-infra/scripts/library.sh
vendor/modules.txt

Produced via:
`./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/cc tcnghia

[master] Auto-update dependencies

---

config/dummy.go

Add dummy.go to make config/ importable
/cc @tcnghia @ZhiminXiang

Add dummy.go to make config/ importable

---

hack/update-deps.sh

Add networking to the least of floating deps

---

pkg/reconciler/ingress/ingress.go

When creating wildcard gateways, we already traverse Istio Gateway service: https://github.com/knative/net-istio/blob/master/pkg/reconciler/ingress/resources/gateway.go#L126
Therefore, there is no need to put them under the loop again.

Move wildcard gateway reconciliation out of the Istio Ingress Gateway loop 

---

hack/tools.go
test/config/chaosduck.yaml
test/e2e-common.sh
vendor/knative.dev/pkg/kflag/doc.go
vendor/knative.dev/pkg/kflag/set.go
vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
vendor/modules.txt

Enable chaos testing on net-istio

---

pkg/reconciler/ingress/ingress.go
pkg/reconciler/ingress/ingress_test.go

Related to: https://github.com/knative/pkg/issues/1520

Drop the event emission on every kingress reconcile.

---

pkg/reconciler/ingress/lister.go
pkg/reconciler/ingress/lister_test.go

Fixes #188.
* Renamed `gatewayHosts` to `hostsByGateway` because it is clearer
* Pick the first host instead of all of them

Probe a single host instead of every hosts

---

pkg/reconciler/ingress/ingress.go
pkg/reconciler/ingress/resources/gateway.go
pkg/reconciler/ingress/resources/gateway_test.go
pkg/reconciler/ingress/resources/secret.go

Replace the DEPRECATED Track method
The pull bot rolled back my code and closed PR. So I created a PR again. @vagababov 
Previous PR https://github.com/knative-sandbox/net-istio/pull/204

Replace the DEPRECATED Track method

---

test/conformance/ingress_test.go
test/e2e-tests.sh

Turn it up to 11

---

config/400-webhook-peer-authentication.yaml

Fixes #150.
/assign @nak3 @tcnghia

Exclude Webhooks from mTLS STRICT

---

pkg/reconciler/ingress/ingress_test.go

Fix the deletes for the new pkg update

---

.golangci.yaml
pkg/reconciler/accessor/errors.go
pkg/reconciler/ingress/ingress_test.go

As per title. Prep work for knative-sandbox/.github#13 to land in sandbox.

Add linting config and fix issues.

---

config/500-mutating-webhook.yaml
config/500-validating-webhook.yaml

Move Webhooks to v1 API.

---

pkg/reconciler/accessor/core/secret_test.go
pkg/reconciler/accessor/istio/virtualservice_test.go
pkg/reconciler/accessor/networking/certificate_test.go
pkg/reconciler/ingress/config/istio_test.go
pkg/reconciler/ingress/config/store_test.go
pkg/reconciler/ingress/ingress_test.go
pkg/reconciler/ingress/lister_test.go
pkg/reconciler/ingress/resources/gateway_test.go
pkg/reconciler/ingress/resources/secret_test.go
pkg/reconciler/ingress/resources/virtual_service_test.go

/assign @tcnghia @ZhiminXiang mattmoor

Fix net istio for proper test formatting

---

pkg/reconciler/ingress/ingress.go

As a departure from the standard procedure this one actually was broken
and required manual interaction :-)
/assign @tcnghia @ZhiminXiang

Fix the format here

---

.golangci.yaml
pkg/reconciler/ingress/ingress.go
pkg/reconciler/ingress/ingress_test.go
pkg/reconciler/ingress/resources/gateway.go
pkg/reconciler/ingress/resources/virtual_service.go
test/e2e/clients.go

- Removed unused code.
- Fixed potentially dangerous memory aliasing.
- Documented blank import.

Enable extended linting and fix the respective issues

---

.codecov.yaml

Make the Codecov settings uniform

---

DEVELOPMENT.md

Add instruction for installing Istio for development purpose

---

DEVELOPMENT.md

Produced via:
```shell
prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github | grep -v docs/cmd/)
```
/cc nak3 ZhiminXiang tcnghia
/assign nak3 ZhiminXiang tcnghia

[Automated] Format markdown

---

go.mod
go.sum
vendor/knative.dev/pkg/configmap/store.go
vendor/knative.dev/pkg/metrics/config_observability.go
vendor/knative.dev/pkg/tracing/config/tracing.go
vendor/modules.txt

Produced via:
```shell
./hack/update-deps.sh --upgrade
./hack/update-codegen.sh
```
/cc nak3 ZhiminXiang tcnghia
/assign nak3 ZhiminXiang tcnghia

[master] Upgrade to latest dependencies

---

third_party/istio-latest/install-istio.sh

Fixes #387.
/assign @arturenault @nak3

Update Istio latest to 1.7.4.

---

config/400-webhook-peer-authentication.yaml

Remove the trailing space

---

hack/release.sh
test/e2e-common.sh
test/upload-test-images.sh

- :gift: Build images for all the platforms ko supports. This matches what we already do in serving and `net-contour` as of https://github.com/knative-sandbox/net-contour/pull/285. Of course, users will still need an appropriate version of istio itself for each platform, but this makes sure knative can be deployed once those exist for a platform.
```release-note
Images are now multi-platform and support architectures such as `arm64`.
```
**Docs**
```docs
```

Build for all platforms

---

third_party/istio-latest/install-istio.sh
third_party/istio-latest/istio-ci-mesh.yaml
third_party/istio-latest/istio-ci-no-mesh.yaml
third_party/istio-latest/istio-kind-mesh.yaml
third_party/istio-latest/istio-kind-no-mesh.yaml
third_party/istio-latest/istio-minimal.yaml

- Update istio-latest to 1.8.1.

Update istio-latest to 1.8.1

---

config/config.yaml
pkg/reconciler/ingress/config/istio.go
pkg/reconciler/ingress/ingress.go
pkg/reconciler/ingress/ingress_test.go

Get status of VirtualService if available and use that to determine ingress readiness

---

third_party/istio-latest/install-istio.sh

- Test VirtualService status feature in istio-latest e2e-tests

Run istio status tests in istio-latest

---

third_party/istio-stable/install-istio.sh

Fixes #455
/assign @arturenault

Update Istio stable to 1.7.6.

---

pkg/reconciler/ingress/config/istio.go
pkg/reconciler/ingress/config/istio_test.go

- Add test for VirtualService status config.

Add test for virtualservice status config

---

third_party/istio-latest/install-istio.sh

Update istio-latest to 1.8.2

---

pkg/reconciler/ingress/ingress.go
pkg/reconciler/ingress/ingress_test.go
pkg/reconciler/ingress/resources/gateway.go

- fix comments
- reorder code for easier ready
- remove unnecessary variables
- preallocate sets
/assign @tcnghia @JRBANCEL

Various cleanups

---

.golangci.yaml
pkg/reconciler/accessor/errors.go
pkg/reconciler/ingress/resources/util.go

This patch is same with https://github.com/knative/serving/commit/b9aa31539112a635ee9887ac7d3ee68081ecc6c8.
It adds errorlint and fixes the lint issues.
/kind cleanup
```release-note
NONE
```
/cc @vagababov @ZhiminXiang

Add errorlint and fix all existing issues

---

pkg/reconciler/ingress/ingress.go
pkg/reconciler/ingress/ingress_test.go

/kind bug
Fixes https://github.com/knative/serving/issues/10710

Ignore status if ObservedGeneration == 0

---

third_party/download-istio.sh
third_party/istio-head/README.md
third_party/istio-head/extra/configure-istio.sh
third_party/istio-head/extra/global-mtls.yaml
third_party/istio-head/install-istio.sh
third_party/istio-head/istio-ci-mesh.yaml
third_party/istio-head/istio-ci-no-mesh.yaml
third_party/istio-head/istio-kind-mesh.yaml
third_party/istio-head/istio-kind-no-mesh.yaml
third_party/istio-head/istio-minimal.yaml

- Add `istio-head` under third-party, giving us the ability to install Istio from HEAD. 
- Makes progress on #496.

Add ability to install istio from HEAD

---

go.mod

As per title. Other repos have long moved.
/assign @nak3

Bump Golang version to 1.15

---

third_party/istio-stable/install-istio.sh

See #503.
Let's see if that is the issue.
/assign @nak3 @arturenault

Temporarily disable mTLS STRICT in mesh mode.

---

third_party/istio-latest/install-istio.sh

Fixes #533 
/assign @arturenault

Update Istio latest to 1.9.1.

---

pkg/reconciler/accessor/core/secret_test.go
pkg/reconciler/accessor/istio/virtualservice_test.go
pkg/reconciler/accessor/networking/certificate_test.go
pkg/reconciler/ingress/ingress_test.go

See https://github.com/knative/pkg/pull/2055 for why this is better :).
/assign @nak3 @ZhiminXiang

Use RunAndSyncInformers in all tests to ensure consistency

---

config/config.yaml

- :broom: Document that enable-virtualservice-status feature is experimental (especially since the upstream istio feature is not ready for prime-time yet, based on [conversations in slack](https://knative.slack.com/archives/CA9RHBGJX/p1617742786033100?thread_ts=1617690611.013200&cid=CA9RHBGJX))
/kind documentation
/assign @nak3

Document that enable-virtualservice-status feature is experimental

---

third_party/istio-head/istio-ci-mesh/istio.yaml
third_party/istio-head/istio-ci-no-mesh/istio.yaml
third_party/istio-head/istio-kind-mesh/istio.yaml
third_party/istio-head/istio-kind-no-mesh/istio.yaml
third_party/istio-head/istio-minimal/istio.yaml
third_party/istio-latest/istio-ci-mesh/istio.yaml
third_party/istio-latest/istio-ci-no-mesh/istio.yaml
third_party/istio-latest/istio-kind-mesh/istio.yaml
third_party/istio-latest/istio-kind-no-mesh/istio.yaml
third_party/istio-latest/istio-minimal/istio.yaml
third_party/istio-stable/istio-ci-mesh/istio.yaml
third_party/istio-stable/istio-ci-no-mesh/istio.yaml
third_party/istio-stable/istio-kind-mesh/istio.yaml
third_party/istio-stable/istio-kind-no-mesh/istio.yaml
third_party/istio-stable/istio-minimal/istio.yaml
third_party/library.sh

This PR orders the resources applied to help mitigate the installation flakes when using `kubectl apply -f istio.yaml`
/assign @nak3 @arturenault

install resources in a particular order

---

third_party/library.sh

fixes https://github.com/knative-sandbox/net-istio/issues/607

drop ignore-unknown-comments

---

pkg/reconciler/accessor/istio/destinationrule_test.go
pkg/reconciler/accessor/istio/virtualservice_test.go
pkg/reconciler/accessor/networking/certificate_test.go

This patch adds unit test for NotOwnedFailure of VirtualService,
DestinationRule and Certificate.

Add NotOwnedFailure test

---

.github/workflows/knative-style.yaml
pkg/reconciler/ingress/ingress.go
pkg/reconciler/ingress/resources/gateway.go

This patch fixes the new lint error exposed by https://github.com/knative-sandbox/net-istio/pull/641/files.

Fix lint issue

---

pkg/reconciler/ingress/ingress.go

We don't need this code as we are already above 0.18 release.

Remove the unneeded code

---

config/config.yaml

The current comment explains about v0.3 which is too old.

Update comment about Gateway in configmap

---

cmd/controller/main.go
cmd/webhook/main.go
config/400-webhook-peer-authentication.yaml
config/500-mutating-webhook.yaml
config/500-validating-webhook.yaml
config/500-webhook-secret.yaml
config/controller.yaml
config/webhook-deployment.yaml
test/e2e-common.sh

Part of https://github.com/knative/networking/issues/448

rename to be consistent with various net-* repos

---

.github/workflows/kind-e2e.yaml
go.mod

As per title, make consistent with other repos.

Bump Golang version to 1.16

---

hack/update-codegen.sh
third_party/istio-latest/generate-manifests.sh
third_party/istio-latest/istio-ci-mesh/istio.yaml
third_party/istio-latest/istio-ci-no-mesh/istio.yaml
third_party/istio-latest/istio-kind-mesh/istio.yaml
third_party/istio-latest/istio-kind-no-mesh/istio.yaml
third_party/istio-stable/generate-manifests.sh
third_party/istio-stable/istio-ci-mesh/istio.yaml
third_party/istio-stable/istio-ci-no-mesh/istio.yaml
third_party/istio-stable/istio-kind-mesh/istio.yaml
third_party/istio-stable/istio-kind-no-mesh/istio.yaml

This patch updates istio versions as:
- before
- istio-stable 1.9.6
- istio-latest 1.10.2 
- after
- istio-stable 1.10.3
- istio-latest 1.11.0
/cc @ZhiminXiang @dprotaso 
Fix https://github.com/knative-sandbox/net-istio/issues/721

Bump Istio stable and latest to 1.10.3 and 1.11.0

---

hack/release.sh

- drop --strict ko flag blocking build

[release-0.22] drop ko strict

---

third_party/istio-head/istio-ci-mesh.yaml
third_party/istio-head/istio-ci-mesh/istio.yaml
third_party/istio-head/istio-ci-no-mesh/istio.yaml
third_party/istio-head/istio-kind-no-mesh/istio.yaml

istio-head does not bump generated istio yaml automatically ass https://github.com/knative-sandbox/net-istio/blob/f92596ff8ae2b2a2b37def30944bb234561c91b4/hack/update-codegen.sh#L64-L66
this patch bumps istio-head manually.
/assign @dprotaso

Bump Istio head

---

third_party/istio-latest/generate-manifests.sh
third_party/istio-latest/istio-ci-mesh/istio.yaml
third_party/istio-latest/istio-ci-no-mesh/istio.yaml
third_party/istio-latest/istio-kind-no-mesh/istio.yaml

Fix https://github.com/knative-sandbox/net-istio/issues/851
Just modified `./third_party/istio-latest/generate-manifests.sh` and `./hack/update-codegen.sh`.
/cc @ZhiminXiang

Bump Istio to 1.12.2

---

third_party/istio-latest/generate-manifests.sh
third_party/istio-latest/istio-ci-mesh/istio.yaml
third_party/istio-latest/istio-ci-no-mesh/istio.yaml
third_party/istio-latest/istio-kind-no-mesh/istio.yaml

As per title, this patch bumps Istio version to 1.13.0
Fix https://github.com/knative-sandbox/net-istio/issues/871

Bump Istio 1.13.0

---

third_party/library.sh

update ytt package name

---

.github/workflows/kind-e2e.yaml

As per title, this patch bumps k8s version in KinD.

Bump k8s version in KinD

---

third_party/istio-latest/generate-manifests.sh
third_party/istio-latest/istio-ci-mesh/istio.yaml
third_party/istio-latest/istio-ci-no-mesh/istio.yaml
third_party/istio-latest/istio-kind-no-mesh/istio.yaml

- :broom: Update Istio to version 1.13.2
/kind cleanup
Fixes #887

Update Istio version to 1.13.2

---

ISTIO.md
hack/update-codegen.sh

This patch adds the doc how to update Istio manifest under third_party.

Add doc how to update Istio manifest

---

third_party/istio-latest/generate-manifests.sh
third_party/istio-latest/istio-ci-mesh/istio.yaml
third_party/istio-latest/istio-ci-no-mesh/istio.yaml
third_party/istio-latest/istio-kind-no-mesh/istio.yaml

- bump istio manifests to 1.13.3
/kind cleanup
Fixes #924

bump istio manifests to 1.13.3

---

third_party/istio-latest/generate-manifests.sh
third_party/istio-latest/istio-ci-mesh/istio.yaml
third_party/istio-latest/istio-ci-no-mesh/istio.yaml
third_party/istio-latest/istio-kind-no-mesh/istio.yaml

- Bumps istio manifests to 1.14.1
Fixes #944

bump istio manifests to 1.14.1

---

go.mod
go.sum
vendor/knative.dev/hack/README.md
vendor/knative.dev/hack/infra-library.sh
vendor/knative.dev/hack/library.sh
vendor/knative.dev/hack/presubmit-tests.sh
vendor/knative.dev/hack/release.sh
vendor/modules.txt

pull in latest knative.dev/hack changes

---

hack/release.sh

platform flag is supplied by hack/release.sh lib
/assign @carlisia @nak3 @AngeloDanducci

fix the release script

---

third_party/istio-latest/generate-manifests.sh
third_party/istio-latest/istio-ci-mesh/istio.yaml
third_party/istio-latest/istio-ci-no-mesh/istio.yaml
third_party/istio-latest/istio-kind-no-mesh/istio.yaml

- bump istio manifests to 1.14.3
- 
Fixes #961

bump istio manifests to 1.14.3

---

third_party/istio-latest/generate-manifests.sh
third_party/istio-latest/istio-ci-mesh/istio.yaml
third_party/istio-latest/istio-ci-no-mesh/istio.yaml
third_party/istio-latest/istio-kind-no-mesh/istio.yaml

- Bump to Istio 1.15.0
Fixes #975

bump istio manifests to 1.15.0

---

config/500-controller.yaml
config/500-webhook-deployment.yaml

- Follows with the pod security admission reqs
- Aligns with https://github.com/knative/serving/pull/13327

Fix psp in config manifests

---

.github/workflows/kind-e2e.yaml

Signed-off-by: Kenny Leung <kleung@chainguard.dev>
- 🧹 bump kind to 0.17.0
/kind cleanup
Fixes #
```release-note
NONE
```
**Docs**
```docs
```

bump kind to 0.17.0

---

third_party/istio-latest/generate-manifests.sh
third_party/istio-latest/istio-ci-mesh/istio.yaml
third_party/istio-latest/istio-ci-no-mesh/istio.yaml
third_party/istio-latest/istio-kind-no-mesh/istio.yaml

Signed-off-by: Kenny Leung <kleung@chainguard.dev>
- 🎁 use istio 1.16.0 manifests
/kind cleanup
Fixes #
```release-note
use istio 1.16.0 manifests
```
**Docs**
```docs
```

use istio 1.16.0 manifests

---

third_party/istio-latest/generate-manifests.sh
third_party/istio-latest/istio-ci-mesh/istio.yaml
third_party/istio-latest/istio-ci-no-mesh/istio.yaml
third_party/istio-latest/istio-kind-no-mesh/istio.yaml

Fixes CVEs
https://istio.io/latest/news/releases/1.15.x/announcing-1.15.6/

[release-1.8] bump istio to v1.15.6

---

test/config/config-logging.yaml
test/e2e-tests.sh
third_party/istio-latest/generate-manifests.sh
third_party/istio-latest/istio-ci-mesh.yaml
third_party/istio-latest/istio-ci-mesh/istio.yaml
third_party/istio-latest/istio-ci-no-mesh.yaml
third_party/istio-latest/istio-ci-no-mesh/istio.yaml
third_party/istio-latest/istio-kind-no-mesh.yaml
third_party/istio-latest/istio-kind-no-mesh/istio.yaml

Resolves - https://github.com/knative/serving/issues/13712

bump istio to v1.17.1

---

third_party/istio-latest/istio-ci-mesh.yaml
third_party/istio-latest/istio-ci-mesh/istio.yaml
third_party/istio-latest/istio-ci-no-mesh.yaml
third_party/istio-latest/istio-ci-no-mesh/istio.yaml
third_party/istio-latest/istio-kind-no-mesh.yaml
third_party/istio-latest/istio-kind-no-mesh/istio.yaml
third_party/library.sh
third_party/upgrade-resource-versions.ytt.yaml

PR was merged while I had some debugging setup
https://github.com/knative-sandbox/net-istio/pull/1068#issuecomment-1462182728
Also dropped our patches to upgrade API versions to autoscaling/v2 and policy/v1
/assign @nak3

Drop access logging & unneeded patches

---

cmd/webhook/main.go
config/500-controller.yaml
config/500-webhook-deployment.yaml

- Add probes to net-istio-controller and net-istio-webhook

Add missing probes

---

config/500-controller.yaml
config/500-webhook-deployment.yaml

Part of https://github.com/knative/serving/issues/13984

drop safe-to-evict annotations

---

config/400-config-istio.yaml

- Documentation about the new configuration format
/kind <kind>
Fixes #

docs: Add documentation about the new config format (#1247)

---

config/400-config-istio.yaml

- Fix documentation behavior description if both old and new format are defined
/kind documentation
Fixes #
```release-note
```
**Docs**
```docs
```

docs: Fix description if old & new format are defined

---

config/400-config-istio.yaml

- Update configmap documentation related to this one: https://github.com/knative-extensions/net-istio/pull/1250
/kind documentation
Fixes #
```release-note
```
**Docs**
```docs
```

docs: Update net-istio configmap documentation (#1248)

---

.github/workflows/kind-e2e.yaml

use knative/actions/setup-go and drop periodic testing

---

third_party/istio-latest/generate-manifests.sh
third_party/istio-latest/istio-ci-ambient/istio.yaml
third_party/istio-latest/istio-ci-mesh/istio.yaml
third_party/istio-latest/istio-ci-no-mesh/istio.yaml
third_party/istio-latest/istio-kind-ambient/istio.yaml
third_party/istio-latest/istio-kind-no-mesh/istio.yaml

[release-1.12] bump istio to v1.19.7

---

.ko.yaml

Part of https://github.com/knative/serving/pull/15310

use cgr.dev/chainguard/static:latest which is nonroot

---

config/placeholder.go
pkg/reconciler/accessor/core/secret.go
pkg/reconciler/accessor/core/secret_test.go
pkg/reconciler/accessor/errors.go
pkg/reconciler/accessor/errors_test.go
pkg/reconciler/accessor/istio/destinationrule.go
pkg/reconciler/accessor/istio/destinationrule_test.go
pkg/reconciler/accessor/istio/virtualservice.go
pkg/reconciler/accessor/istio/virtualservice_test.go
pkg/reconciler/accessor/networking/certificate.go
pkg/reconciler/accessor/networking/certificate_test.go
pkg/reconciler/ingress/config/istio.go
pkg/reconciler/ingress/config/istio_test.go
pkg/reconciler/ingress/config/store.go
pkg/reconciler/ingress/config/store_test.go
pkg/reconciler/ingress/ingress_test.go
pkg/reconciler/ingress/lister.go
pkg/reconciler/ingress/resources/gateway.go
pkg/reconciler/ingress/resources/gateway_test.go
pkg/reconciler/ingress/resources/names/doc.go
pkg/reconciler/ingress/resources/virtual_service_test.go
pkg/reconciler/serverlessservice/serverlessservice_test.go
test/e2e-common.sh
test/e2e-tests.sh
test/upload-test-images.sh

/assign @skonto 
reported in https://github.com/knative-extensions/net-istio/pull/1341

fix boilerplate

---

pkg/reconciler/ingress/ingress.go
pkg/reconciler/ingress/ingress_test.go

Fixes: https://github.com/knative-extensions/net-istio/issues/1407

allow removing the finalizer if a gateway is missing

---

.golangci.yaml

fix golangci-lint config

---

.golangci.yaml

- **bump to golangci yaml v2**
- **fix config**

update golangci lint
