hack/release.sh
This should unblock the nightly releases currently failing [here](https://testgrid.knative.dev/net-istio#nightly), and enable us to release things by simply cutting a branch for 0.14.
This is based on `net-contour`'s, which I based on `eventing`'s equivalent script.
Related: https://github.com/knative/serving/issues/7039
=> Add `hack/release.sh` to unblock releasing `net-istio`.

pkg/defaults/deployment_defaults.go, pkg/defaults/deployment_defaults_test.go
I accidentally copied the wrong label name. The label name is "canonical-name" not "canonical-service":
https://docs.google.com/document/d/1EsKpYNW55-LqG08zdjp1tAd224T9IEG3CEnusmL-Joc/edit#heading=h.lxsagz3b8886.
I have asked about exporting the label strings from istio side. Currently it's exported on pilot, and I don't think this should have a dependency on pilot: https://github.com/istio/istio/blob/2d1b8d6fc2a30787d397770e6f6aa1eec6a46b03/pilot/pkg/model/service.go#L151
=> Fix name for istio canonical service names.

pkg/reconciler/accessor/core/secret.go, pkg/reconciler/ingress/ingress.go, pkg/reconciler/ingress/ingress_test.go, pkg/reconciler/ingress/resources/gateway.go, pkg/reconciler/ingress/resources/secret.go, pkg/reconciler/ingress/resources/secret_test.go
1. Remove the cross-namespace OwnerReference added when copying secret from user's application namespace to Istio gateway namespace
2. Explicitly delete the secret resources when Ingress is being deleted.
https://github.com/knative/serving/issues/7305
=> Remove the cross namespace OwnerReference

pkg/reconciler/ingress/resources/virtual_service.go, pkg/reconciler/ingress/resources/virtual_service_test.go
This patch removes deprecated value `websocketUpgrade` from VirtualService.
Fixes https://github.com/knative/net-istio/issues/53
=> Remove obsoleted WebsocketUpgrade from VirtualService

pkg/reconciler/ingress/ingress.go
This patch make a tiny change to fix log format.
The log missed `%v` so it wrongly prints the log as:
`kubelogs.go:157: E 01:49:53.850 [istio-ingress-controller] [serving-tests/autoscale-sustaining-yjsgcahk] Failed to reconcile Ingress autoscale-sustaining-yjsgcahk%!!(MISSING)(EXTRA *fmt.wrapError=failed to update Gateway: Operation cannot be fulfilled on gateways.networking.istio.io "knative-ingress-gateway": the object has been modified; please apply your changes to the latest version and try again)`
=> Fix log format issue

pkg/reconciler/ingress/config/istio.go, pkg/reconciler/ingress/config/istio_test.go
When gateway service URL has the dot at the end, the validation check
fails currently. It should be valid as a FQDNS.
This patch trims the trailing dot to allow service URL has the dot at
the end.
Fixes https://github.com/knative/serving/issues/7415
=> Allow trailing dot for gateway service URL

pkg/reconciler/ingress/lister.go, pkg/reconciler/ingress/lister_test.go
Fixes https://github.com/knative/serving/issues/7294
Setup: 5 Envoy Pods
```
0.165s The Route is still working to reflect the latest desired specification.
0.417s Configuration "helloworld-go" is waiting for a Revision to become ready.
3.182s ...
3.365s Ingress has not yet been reconciled.
3.592s Waiting for load balancer to be ready
4.924s Ready to serve.
```
```
0.215s The Route is still working to reflect the latest desired specification.
0.274s Configuration "helloworld-go" is waiting for a Revision to become ready.
3.150s ...
3.354s Ingress has not yet been reconciled.
3.463s Waiting for load balancer to be ready
43.610s Ready to serve.
```
```
0.149s The Route is still working to reflect the latest desired specification.
0.374s Configuration "helloworld-go" is waiting for a Revision …
```
=> Coalesce the Gateway.spec.servers[] with the same port and protocol

pkg/reconciler/ingress/lister.go, pkg/reconciler/ingress/lister_test.go
When mutual TLS is configured on the gateway, a probe is attempted, but is rejected because the caller does not have a client certificate present. With the `knative-ingress-gateway` configured like the following:
```yaml
spec:
selector:
istio: ingressgateway
servers:
- hosts:
- '*'
port:
name: https
number: 443
protocol: HTTPS
tls:
credentialName: knative-ingress-gateway-tls
minProtocolVersion: TLSV1_3
mode: MUTUAL
```
The v0.13.2 networking-istio operator dumps log lines like the following:
```
{
"level": "error",
"ts": "2020-04-19T00:47:41.053Z",
"logger": "istiocontroller.istio-ingress-controller.status-manager",
"caller": "status/status.go:378",
"msg": "Probing of https://hello-world-hello-world.ai1.cluster.k8s.local:443 failed, IP: 10.11.57.191:443, ready: false, error: error …
```
=> ingress: Skip gateway servers with mutual TLS configured

pkg/reconciler/ingress/ingress.go, pkg/reconciler/ingress/ingress_test.go
This is to fix the issue that arises if someone migrates from 0.11- to 0.13+.
In Knative 0.13, the way the name of one of the `VirtualService` is derived from the `Ingress` name changed from `{IngressName}` to `{IngressName}-ingress`. The controller is cleaning the old `VirtualService`, see [code](https://github.com/knative/net-istio/blame/master/pkg/reconciler/ingress/ingress.go#L226), but this is done with the label `networking.internal.knative.dev/ingress` which was introduced in 0.12.
As a result, there are two `VirtualService` matching the same requests. Because the way Istio creates the Envoy configuration is not deterministic, which rule is first (and therefore matching) is random. This means that for each `VirtualService` change, there is a 50% chance that the new `VirtualService` …
=> Also delete VirtualServices created before Knative 0.12

config/500-mutating-webhook.yaml, config/500-validating-webhook.yaml, config/500-webhook-secret.yaml, config/webhook-deployment.yaml, config/webhook-service.yaml
This patch adds the label `networking.knative.dev/ingress-provider: istio` to webhook resources.
As the `net-istio.yaml` in the [serving project](https://github.com/knative/serving/blob/e315571c47686a17f622e0fd29552baaedde07b0/config/net-istio.yaml) does not have the label in webhook resources, it installs them unexpectedly:
```
$ cd $GOPATH/src/knative.dev/serving
$ ko apply -f config/ --selector=networking.knative.dev/ingress-provider!=istio
...
mutatingwebhookconfiguration.admissionregistration.k8s.io/webhook.istio.networking.internal.knative.dev created
validatingwebhookconfiguration.admissionregistration.k8s.io/config.webhook.istio.networking.internal.knative.dev created
secret/istio-webhook-certs created
deployment.apps/istio-webhook created
service/istio-webhook created
``` …
=> Add ingress-provider label to webhook

go.mod, hack/tools.go, vendor/knative.dev/serving/test/test_images/helloworld/README.md, vendor/knative.dev/serving/test/test_images/helloworld/helloworld.go, vendor/knative.dev/serving/test/test_images/helloworld/helloworld.yaml, vendor/knative.dev/serving/test/test_images/helloworld/service.yaml, vendor/modules.txt
This moves go.mod to go 1.14 to automatically detect the vendor directory. It also adds the missing helloworld image to make tests pass again. Without it, `upload-test-image.sh` will fail.
=> Fix presubmit tests to use vendor and have all images.

pkg/reconciler/ingress/resources/gateway.go, pkg/reconciler/ingress/resources/gateway_test.go, pkg/reconciler/ingress/resources/secret.go, pkg/reconciler/ingress/resources/secret_test.go
Context: https://github.com/knative/serving/issues/7495#issuecomment-609369477
For Ingresses sharing a wildcard certificate, they need to be tied to a Gateway with the wildcard host.
This PR adds the helper function to generate wildcard Gateway with the given wildcard certificate secret.
=> Add Gateway related helper functions for generating Gateway for wildcard certificate

cmd/controller/main.go
Fixes https://github.com/knative/serving/issues/7320.
=> Allow unknown fields in VirtualService and Gateway deserialization

Gopkg.lock, Gopkg.toml, pkg/reconciler/ingress/lister.go, pkg/reconciler/ingress/lister_test.go, vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go, vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go, vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go, vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go, vendor/knative.dev/serving/test/test_images/helloworld/README.md, vendor/knative.dev/serving/test/test_images/helloworld/helloworld.go, vendor/knative.dev/serving/test/test_images/helloworld/helloworld.yaml, vendor/knative.dev/serving/test/test_images/helloworld/service.yaml
This PR ports the changes from #67 back to the 0.14 branch to make the performance improvements available in Knative 0.14.x
=> Backport "Coalescing the Gateway.spec.servers[]" #67 to the 0.14 branch

pkg/reconciler/ingress/resources/virtual_service.go, pkg/reconciler/ingress/resources/virtual_service_test.go
To adapt the changes introduced by https://github.com/knative/serving/pull/6036, 
, `headers` field of KIngress is translated into the `header` field of `VirtualService` by this PR.
=> Support for header-matching

pkg/reconciler/ingress/resources/virtual_service.go, pkg/reconciler/ingress/resources/virtual_service_test.go
This patch changes to set `istiov1alpha3.HTTPRetry.Attempts` to 0 when
no retries are configued or attempts are set to 0.
Istio tries to retry twice before returning the error by
default. Please refer to the following istio doc:
https://istio.io/latest/docs/concepts/traffic-management/#retries
> The default retry behavior for HTTP requests is to retry twice before returning the error.
fix https://github.com/knative/serving/issues/6549
=> Explicitly set retry attempt to 0 when no retries are configured in ingress

go.mod, go.sum, vendor/knative.dev/pkg/webhook/admission.go, vendor/knative.dev/pkg/webhook/conversion.go, vendor/knative.dev/pkg/webhook/webhook.go, vendor/modules.txt
* This includes webhook fixes that should make upgrading from 0.15 to 0.16 smooth
```release-note
Webhook responses now return TypeMeta which would interrupt serving upgrades 
```
=> [release-0.15] update knative.dev/pkg which includes webhook fixes

pkg/reconciler/ingress/ingress.go, pkg/reconciler/ingress/ingress_test.go, pkg/reconciler/ingress/lister.go, pkg/reconciler/ingress/lister_test.go, pkg/reconciler/ingress/resources/virtual_service.go, pkg/reconciler/ingress/resources/virtual_service_test.go
Implementation of https://github.com/knative/serving/issues/7748.
Note: it's not really sensible to try probing with a RewriteHost rule since we can't ensure the hash is what we expect, or even present (since it's returned by a different service), so this just skips probing if a RewriteHost rule is used.
Conformance test in serving: https://github.com/knative/serving/pull/8592.
/assign @tcnghia @mattmoor
=> Implement RewriteHost

pkg/reconciler/ingress/resources/virtual_service.go, pkg/reconciler/ingress/resources/virtual_service_test.go
Following on from @ZhiminXiang's [suggestion](https://github.com/knative-sandbox/net-istio/pull/174#discussion_r456184487) in  https://github.com/knative-sandbox/net-istio/pull/174, better to always target the cluster local gateway in RewriteHost rules, since the user may want to set up https/authentication on the external gateway that might otherwise get in the way of the request.
/assign @ZhiminXiang @tcnghia
=> Always target cluster local gateway for RewriteHost rules

pkg/reconciler/ingress/lister_test.go
Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -path './third_party' -prune -o -name '*.pb.go' -prune -o -type f -name '*.go' -print)`
`goimports -w $(find -name '*.go' | grep -v vendor | grep -v third_party | grep -v .pb.go | grep -v wire_gen.go)`
/cc tcnghia
=> [master] golang format tools

go.mod, go.sum, vendor/knative.dev/test-infra/scripts/e2e-tests.sh, vendor/modules.txt
This pulls in https://github.com/knative/test-infra/pull/2360 to reduce pressure on `kube-dns`.
=> Run tests with NodeLocalDNS enabled

test/conformance/ingress_test.go
This will bring the load a bit  closer to the level of concurrency we see in Serving e2e tests.
=> Run 5 parallel invocations for KIngress conformance tests.

test/conformance/ingress_test.go, test/e2e-tests.sh
I'm trying to reproduce the flakiness of Istio 1.5 when running conformance tests.
=> Remove `-parallel=12` to match Serving e2e & increase test runs.

config/203-local-gateway.yaml, pkg/reconciler/ingress/config/istio.go
Related to https://github.com/knative-sandbox/net-istio/issues/212.
The idea is to create a new `Gateway` named `knative-local-gateway` (more consistent with `knative-ingress-gateway` than `cluster-local-gateway`). This Gateway binds to the same Envoy Pods as the Istio ingress Gateway, but on a different port (`8081` because `8080` is already used by Istio). There is a corresponding Kubernetes Service mapping named `knative-local-gateway` living in `knative-serving` (cleaner than `cluster-local-gateway` living in `istio-system`) mapping port `80` to port `8081`.
`knative-local-gateway` is added to the default Istio Gateways, this way the VirtualServices of local Knative Services bind to it (i.e. ready to serve traffic), but because the `KIngress` status uses the first local Gateway in its …
=> Add new local Gateway sharing same deployment as ingress Gateway.

third_party/istio-1.5.7-helm/istio-ci-no-mesh.yaml, third_party/istio-1.5.7-helm/istio-minimal.yaml, third_party/istio-1.5.7-helm/values-lean.yaml, third_party/istio-1.5.7-helm/values-local.yaml
This patch add global.mtls.auto to false explicitly in
values-local.yaml and values-lean.yaml.
Without `global.mtls.auto=false`, helm sets
`ISTIO_AUTO_MTLS_ENABLED=true` and gateway tries to find certificates.
It can be solved by specify `global.mtls.auto=false` or deploying
citadel.
/cc @ZhiminXiang 
fix https://github.com/knative-sandbox/net-istio/issues/259
=> Add global.mtls.auto false explicitly in values-local.yaml and values-lean.yaml

test/conformance/ingress_test.go
Instead of running N iterations, just run one when `-short` is passed.
=> Add support for -short

pkg/reconciler/ingress/ingress_test.go
We need to set visibility explicitly in the unit test so that the gateway corresponding to the visibility could be picked up
/assign @JRBANCEL
=> Fix the incorrect unit test when auto TLS is enabled

hack/release.sh
First part of https://github.com/knative/serving/issues/9420.
This way we can clone `net-istio` in `serving` at the exact point `net-istio.yaml` was generated.
No more hard-coding in the scripts.
=> Include HEAD commit hash in release YAML.

third_party/istio-latest/istio-ci-mesh-node-port.yaml, third_party/istio-latest/istio-ci-no-mesh-node-port.yaml, third_party/istio-stable/istio-ci-mesh-node-port.yaml, third_party/istio-stable/istio-ci-no-mesh-node-port.yaml
This allows to deploy Istio with `istio-ingressgateway` Service type `NodePort` instead of `LoadBalancer`.
This is needed for `Kind` and `minikube`.
Fixes #285.
=> Add NodePort Service profiles.

third_party/istio-latest/istio-kind-mesh.yaml, third_party/istio-latest/istio-kind-no-mesh.yaml, third_party/istio-stable/istio-kind-mesh.yaml, third_party/istio-stable/istio-kind-no-mesh.yaml
In #293, I introduced profiles exposing the Ingress Service has a Node Port so that it would work with the Kind E2E running in a GitHub Action. GitHub Actions have only 2 cores, so the `resource.requests` and `replicaCount` need to be scaled way down in order for Istio to be deployed successfully on Kind (https://github.com/knative/serving/pull/9471).
Also, this renames the profiles to make the intent clearer.
=> Rename and tweak Kind profiles.

.codecov.yaml
Currently CodeCov is too strict causing harmless PRs (update deps) to be flagged. This mirrors what we have in Serving and tune things down a little bit.
/assign @mattmoor
=> Tune CodeCov down a little bit.

third_party/istio-latest/extra/global-mtls.yaml, third_party/istio-latest/install-istio.sh, third_party/istio-latest/istio-ci-mesh.yaml, third_party/istio-latest/istio-kind-mesh.yaml
These prevents `latest` from being installed.
=> Remove deprecated fields.

pkg/reconciler/ingress/resources/gateway.go, pkg/reconciler/ingress/resources/virtual_service.go, pkg/reconciler/ingress/resources/virtual_service_test.go
When the incoming request is using https, failing to specify the destination port means we end up re-running the request against port 443 on the cluster-local-gateway which is not what we want.  We see errors like "`Connection #0 to host blah-blah left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure`" when using a rewrite rule over https.  
Explicitly specifying port 80 for the destination fixes our issue (I think the hard-coding of 80 is fine here because this is the only port the cluster local gateway can possibly be on).
This matches the way we already set a port for regular non-rewrite-host splits (see [virtual_service.go#L189](https://github.com/knative-sandbox/net-istio/blob/9fb6d8eee0f12b6cc3bfbc34b646246ef45eafd4/pkg/reconciler/ing …
=> Specify port for rewrite host destination

pkg/reconciler/ingress/ingress_test.go
This patch removes DeprecatedGeneration from ingress test util.
Part of https://github.com/knative/networking/issues/195
/cc @ZhiminXiang @JRBANCEL @dprotaso
=> Remove deprecated generation field

third_party/istio-stable/dummy.go
This patch adds dummy.go in third_party/istio-stable.
After this patch, other repo like knative/docs can pull the directory and
use install-istio.sh and manifest.
/cc @ZhiminXiang @JRBANCEL @mattmoor @tcnghia
=> Add dummy.go to istio stable

pkg/reconciler/ingress/ingress_test.go, pkg/reconciler/ingress/resources/virtual_service.go, pkg/reconciler/ingress/resources/virtual_service_test.go
Ingress's timeout was set to super long timeout by
https://github.com/knative/serving/pull/8965.
But the current conformance test for [omitted timeout ](https://github.com/knative/networking/pull/157) proved that we can drop
the timeout so knative/serving and knative/networking are dropping it.
Please see https://github.com/knative/networking/pull/228 and https://github.com/knative/serving/pull/9852.
Hence this patch removes timeout in net-istio to follow up them.
/cc @ZhiminXiang @JRBANCEL @tcnghia
=> Remove Ingress Timeout

test/e2e/e2e.go
The pkgTest.T/TLegacy interfaces have been deprecated, so remove their usage.
https://github.com/knative/networking/pull/236 is same PR for networking repo.
/cc @ZhiminXiang @markusthoemmes @tcnghia
=> Remove deprecated pkgTest.TLegacy

third_party/istio-latest/istio-kind-mesh.yaml, third_party/istio-latest/istio-kind-no-mesh.yaml, third_party/istio-stable/istio-kind-mesh.yaml, third_party/istio-stable/istio-kind-no-mesh.yaml
When k8s cluster is changed the cluster.local domain, Istio (istio gateway
and sidecar) needs to change the domain by values.global.proxy.
This patch adds the value to replace it easily during KinD e2e.
Please see also https://github.com/knative/serving/issues/9750
/cc @mattmoor @tcnghia @ZhiminXiang @JRBANCEL
=> Add clusterDomain to values.global.proxy in kind yaml to replace it easily

config/203-local-gateway.yaml, pkg/reconciler/ingress/config/istio.go
There was a fatal in [my plan](https://github.com/knative-sandbox/net-istio/pull/237#issue-471304463) to collocate both Ingress and Local Gateways into the same Envoy Pods: k8s service selectors only work inside the same namespace (the Envoy Pods are in `istio-system`).
This moves the `knative-local-gateway` k8s service to `istio-system`, this is fine because this service is not being used yet (see phase #2 of the plan).
Also, this addresses @mattmoor [comment](https://github.com/knative-sandbox/net-istio/pull/237#discussion_r508943888) about using `network.GetServiceHostname`.
=> Move knative-local-gateway service to istio-system.

pkg/reconciler/ingress/config/istio.go
This is phase 2 of #212. 
/hold
DO NOT MERGE UNTIL 0.18 IS RELEASED.
/assign @ZhiminXiang @tcnghia
=> Use knative-local-gateway as only default Gateway.

.github/workflows/kind-e2e.yaml
This patch adds net-istio tests for KinD on github action.
The test also uses random cluster suffix.
Fixes https://github.com/knative-sandbox/net-istio/issues/343 https://github.com/knative-sandbox/net-istio/issues/344 
/cc @ZhiminXiang @JRBANCEL @tcnghia
=> Run net-istio tests on KinD with non-default cluster suffix 

config/400-webhook-peer-authentication.yaml
Fixes #397.
/assign @houshengbo @tcnghia @ZhiminXiang
=> Add missing labels to PeerAuthentication.

hack/release.sh
In https://github.com/knative-sandbox/net-istio/pull/288, the commit was only added to `release.yaml`.
The problem is that in `serving` we copy the component YAML(s) directly, not `release.yaml`.
This includes the commit ID in all component YAML (which also end up in `release.yaml` by concatenation.
=> Include commit ID in component YAML instead of release YAML.

CONTRIBUTING.md
This patch makes a tiny change to replace `sample-controller` with
`net-istio` in CONTRIBUTING.md.
/cc @ZhiminXiang @JRBANCEL @arturenault
=> Replace sample-controller with net-istio in CONTRIBUTING.md

third_party/istio-latest/install-istio.sh, third_party/istio-stable/install-istio.sh
This is a part of https://github.com/knative-sandbox/net-istio/issues/173.
By this patch, it enabled [`MeshOnly` API](https://github.com/knative/networking/blob/59e3a403ce6e06847bd610126cc2a66565fb9fd7/pkg/apis/networking/v1alpha1/ingress_types.go#L337-L339)
in ingress status.
/cc @ZhiminXiang @JRBANCEL @tcnghia
=> Use mesh mode when sidecar injection is enabled

pkg/reconciler/ingress/ingress.go
As per title, our reconcilers do this after reconcilation automatically.
/assign @ZhiminXiang @nak3
=> Drop manually updating observed generation

third_party/istio-latest/install-istio.sh, third_party/istio-stable/install-istio.sh
Supports OSes other than linux in `install-istio.sh`.
/kind bug
Fixes #419
```release-note
install-istio.sh now supports OSes other than linux
```
=> Support OSes other than linux in install-istio.sh

pkg/reconciler/ingress/ingress_test.go
This patch makes a super tiny change which removes extra brackets in table test.
/kind cleanup
```release-note
NONE
```
/cc @ZhiminXiang @JRBANCEL @arturenault
=> Remove extra brackets in table test

third_party/istio-stable/install-istio.sh
Fixes #421.
1.7.4 has been as stable as 1.7.1: https://testgrid.knative.dev/serving#istio-latest-no-mesh
=> Update Istio stable to 1.7.4 and latest to 1.7.5.

test/e2e/probing_test.go
We should use spoof now
Fixes this: https://github.com/knative-sandbox/net-istio/pull/441/checks?check_run_id=1497194142
=> Fix the lint issue.

.github/workflows/kind-e2e.yaml
This patch changes to uses ko 0.6.0.
Currently all github actions are failing as https://github.com/knative-sandbox/net-istio/actions/runs/438456166.
This is same fix with https://github.com/knative-sandbox/net-contour/pull/390.
/kind cleanup
```release-note
NONE
```
=> Use ko 0.6.0 release

pkg/reconciler/ingress/ingress_test.go
- Rename function from `virtualServiceCalledTimes` to `proberCalledTimes`, which is more accurate
- Fix a comment and an error log that both assumed n always == 1.
=> Fix tiny logging/comment/naming bugs in virtualservice status test

hack/release.sh, third_party/download-istio.sh, third_party/istio-latest/install-istio.sh, third_party/istio-stable/extra/istio-namespace.yaml
Fixes  https://github.com/knative/docs/issues/2166.
`hack/release.sh` creates a file named `istio.yaml` so that users can do `kubectl apply -f istio.yaml`.
It is vastly inferior to using `istioctl`, but at least it is consistent and as easy as `kubectl apply -f contour.yaml`
Docs change: https://github.com/knative/docs/pull/3151
/assign @mattmoor @tcnghia 
/hold
=> Release `istio.yaml` to simplify the installation.

pkg/reconciler/ingress/ingress.go
Came here to fix the Debugf, but figured I might as well tidy the function around it up a bit while I was touching it.
- 🧹 `Debugf()` was missing an argument (`vs.Name`) leading to messy log messages.
- 🧹 Add names to return variables since otherwise they're easy to confuse here.
- 🧹 Fix out-of-date method comment (remove err from one, add err to the other :)).
- 🧹 Change comment and log message to say "checking VirtualService status" instead of "probing VS" since probing is exactly what we're checking the VS status to avoid having to do.
- 🧹 We always exit after the first error (since `isVirtualServiceReady` returns "false, false, err" in that case), so remove the error appending and just log and return false straight away instead of storing the exactly-one error up.
- 🧹 Drop the …
=> Clean up some formatting and tidy loop

third_party/placeholder.go
By the change c35f93d, `download-istio.sh` was located in `third_party`
directory.
knative.dev/docs needs to pull `download-istio.sh` so this patch adds
`placholder.go`
```release-note
NONE
```
/cc @JRBANCEL @arturenault
=> Add placeholder.go under third_party

config/400-webhook-peer-authentication.yaml
DomainMapping introduced webhook. Without this configuration,
domainmapping is not created/edited under STRICT mTLS policy.
```release-note
Permissive PeerAuthentication for domainmapping-webhook is included.
```
/cc @ZhiminXiang  @JRBANCEL @arturenault
=> Add permissive PeerAuthentication for domainmapping-webhook

test/e2e-common.sh
- knative/test-infra#2641 enabled mesh tests on pull requests in net-istio, but net-istio didn't support that parameter yet. This should fix that.
=> Fix mesh tests

config/400-webhook-peer-authentication.yaml
Rather than making mTLS permissive on all ports, only open up the one
port that needs to be accessed by the control plane. This places the
metrics and profiling endpoints back under mTLS being required.
This technically enables the minimal carve out needed, and has been how
we have been running the KNative webhooks successfully.
From my perspective it technically improves security - at least as far as auditing is concerned.
The purpose is to reduce the surface area of things running in the cluster that is not covered by mTLS. Whitelisting one port is better than whitelisting the whole service.
```release-note
Make mTLS permissive only on the webhook port. Other ports will go back to using the cluster default setting.
```
**Docs**
N/A?
=> peer auth: Only set permissive mTLS on the webhook port.

pkg/reconciler/ingress/config/testdata/config-istio.yaml, pkg/reconciler/ingress/resources/virtual_service_test.go
This patch cleans up `cluster-local-gateway` in tests.
/kind cleanup
=> Clean up cluster-local-gateway in test code

pkg/reconciler/ingress/resources/virtual_service.go, pkg/reconciler/ingress/resources/virtual_service_test.go
- :bug: Re-introduces the behaviour of explicitly setting retries to zero, needed to override the Istio default of 2 retries. This was introduced in https://github.com/knative-sandbox/net-istio/pull/159 to fix https://github.com/knative/serving/issues/6549, but looks like it was accidentally dropped in https://github.com/knative-sandbox/net-istio/pull/263 when we bumped deps after removing the Retry field from KIngress.
/kind bug
```release-note
Configures Istio not to retry requests. This was accidentally reverted in 0.18.
```
/assign @tcnghia @nak3
=> Re-introduce behaviour of explicitly setting retries to 0

go.mod, go.sum, hack/tools.go, vendor/knative.dev/networking/test/conformance/ingress/retry.go, vendor/knative.dev/networking/test/conformance/ingress/run.go, vendor/knative.dev/networking/test/conformance/ingress/util.go, vendor/knative.dev/networking/test/test_images/retry/main.go, vendor/knative.dev/networking/test/test_images/retry/service.yaml, vendor/modules.txt
This patch adds retry test image which was added by
https://github.com/knative/networking/commit/45b7ed13aeaa6276d6399cec0e3354c8acd8dbd0.
/kind cleanup
```release-note
NONE
```
=> Add retry test image

pkg/reconciler/ingress/resources/virtual_service.go, pkg/reconciler/ingress/resources/virtual_service_test.go
We added support for specifying (actually, a requirement to supply!) splits to the API (https://github.com/knative/networking/pull/107), but the istio implementation was still actually hard-coding the gateway as the backend for RewriteHost rules, and ignoring the splits. 
This changes that so we properly respect the passed splits like the other ingresses do. (In practice none of our current use cases work differently either way so this didn't matter, but that could change and it's good to be consistent).
```release-note
Ingresses with RewriteHost specified now properly respect passed Splits
```
/assign @nak3 @tcnghia
=> Properly implement Splits support in RewriteHost

third_party/istio-stable/extra/istio-namespace.yaml
The release script depends on this file being there in order to correctly assemble the release YAML. It was dropped (accidentally?) in #515.
=> Add namespace to stable's extra folder to fix nightly builds

pkg/reconciler/ingress/resources/gateway.go, pkg/reconciler/ingress/resources/gateway_test.go
Fixes #
https://github.com/knative-sandbox/net-istio/issues/514
```release-note
Fix the incorrect Gateway name format for DomainMapping auto TLS feature for Istio implmenetation
```
=> Handle the case when ingress name has dot

config/config.yaml, pkg/reconciler/ingress/config/istio.go, pkg/reconciler/ingress/config/istio_test.go
Ref https://github.com/knative/serving/issues/10751
Adds a feature flag to allow us to control whether or not the pod addessability stuff is enabled or not, to allow for focused testing and hardening before enabling by default.
/assign @julz @arturenault
=> Add a feature flag to guard pod addressability additions

pkg/reconciler/ingress/resources/virtual_service.go, pkg/reconciler/ingress/resources/virtual_service_test.go
:broom: This change updates the matching mode for rule paths to use prefix matching instead of regular expression matching. The regular expression mode was never correctly implemented by Knative when generating rules, and most other networking layers only support prefix matching anyway.
See the discussion here for more context: https://github.com/knative/networking/pull/364
/kind cleanup
=> Use prefix matching for KIngress rule paths

third_party/istio-head/istio-ci-mesh.yaml, third_party/istio-head/istio-ci-no-mesh.yaml, third_party/istio-head/istio-kind-mesh.yaml, third_party/istio-head/istio-kind-no-mesh.yaml, third_party/istio-head/istio-minimal.yaml, third_party/istio-latest/istio-ci-mesh.yaml, third_party/istio-latest/istio-ci-no-mesh.yaml, third_party/istio-latest/istio-kind-mesh.yaml, third_party/istio-latest/istio-kind-no-mesh.yaml, third_party/istio-latest/istio-minimal.yaml, third_party/istio-stable/istio-ci-mesh.yaml, third_party/istio-stable/istio-ci-no-mesh.yaml, third_party/istio-stable/istio-kind-mesh.yaml, third_party/istio-stable/istio-kind-no-mesh.yaml, third_party/istio-stable/istio-minimal.yaml
We seem to be seeing flaky connections in the Serving E2E test suite due to ingressgateways shutting down during tests. We're configuring this value for mesh pods as well, so maybe this'll help (the default value is 5s).
/hold
For verification in Serving first.
=> Add configuration for graceful shutdown to ingressgateways

pkg/reconciler/accessor/istio/destinationrule.go, pkg/reconciler/accessor/istio/destinationrule_test.go
Ref knative/serving#10751
Adds a helper to reconcile destionationrules the same way we have an accessor for virtualservices. The code is mostly copy and pasted and then the respective resource names have been replaced.
/assign @vagababov @ZhiminXiang
=> Add an accessor for DestinationRule objects

pkg/reconciler/serverlessservice/controller.go, pkg/reconciler/serverlessservice/resources/destinationrule.go, pkg/reconciler/serverlessservice/resources/virtualservice.go, pkg/reconciler/serverlessservice/serverlessservice.go, pkg/reconciler/serverlessservice/serverlessservice_test.go, pkg/reconciler/testing/listers.go
Ref knative/serving#10751
This implements the actual reconciler and its resources. Note that the reconciler still isn't hooked into main so it won't be running after merging this.
=> Implement the SKS reconciler for pod addressability

cmd/controller/main.go, config/200-clusterrole.yaml, test/config/300-serverlessservice.yaml
Ref https://github.com/knative/serving/issues/10751
This enables the new reconciler and adjusts the necessary ClusterRole. Note that the reconciler is disabled by default, i.e. it'll do nothing.
/assign @nak3 @julz @ZhiminXiang @vagababov
=> Start pod addressability reconciler with the controller

third_party/istio-head/istio-ci-mesh.yaml, third_party/istio-head/istio-ci-no-mesh.yaml, third_party/istio-head/istio-kind-mesh.yaml, third_party/istio-head/istio-kind-no-mesh.yaml, third_party/istio-latest/istio-ci-mesh.yaml, third_party/istio-latest/istio-ci-no-mesh.yaml, third_party/istio-latest/istio-kind-mesh.yaml, third_party/istio-latest/istio-kind-no-mesh.yaml, third_party/istio-stable/istio-ci-mesh.yaml, third_party/istio-stable/istio-ci-no-mesh.yaml, third_party/istio-stable/istio-kind-mesh.yaml, third_party/istio-stable/istio-kind-no-mesh.yaml
HPA scaling down ingress gateways causes flakes in CI, which reflect legitimate problems production users might experience.
We tried [bumping the drain time to 20 seconds](https://github.com/knative-sandbox/net-istio/pull/553) but we still see flakes since one test requires at least 35 seconds. In reality this feels like a real problem unless we set the shutdown time to 5 minutes+ (the default max revision timeout), and even then scaling down an ingress gateway will kill long running requests (e.g. websockets).
Bumping the drain time again, to 40 seconds, would also fix the flakes, but would be covering up a real problem that would hit users in production. Disabling autoscaling for the ingress gateway seems like the safer out-of-the-box default for now.
- :bug: Disable autoscaling of …
=> Disable autoscaling for ingress gateways

third_party/istio-head/istio-ci-mesh.yaml, third_party/istio-head/istio-ci-no-mesh.yaml, third_party/istio-head/istio-kind-mesh.yaml, third_party/istio-head/istio-kind-no-mesh.yaml, third_party/istio-latest/istio-ci-mesh.yaml, third_party/istio-latest/istio-ci-no-mesh.yaml, third_party/istio-latest/istio-kind-mesh.yaml, third_party/istio-latest/istio-kind-no-mesh.yaml, third_party/istio-stable/istio-ci-mesh.yaml, third_party/istio-stable/istio-ci-no-mesh.yaml, third_party/istio-stable/istio-kind-mesh.yaml, third_party/istio-stable/istio-kind-no-mesh.yaml
As per title, this fixes https://github.com/knative-sandbox/net-istio/pull/570 which sadly had no effect on autoscaling. This now explicitly disables the HPAs and manually sets the desired replicaCount.
/assign @julz @nak3
=> Properly disable HPA for ingressgateways

pkg/reconciler/serverlessservice/resources/destinationrule.go, pkg/reconciler/serverlessservice/resources/virtualservice.go, pkg/reconciler/serverlessservice/serverlessservice.go, pkg/reconciler/serverlessservice/serverlessservice_test.go
As per title, this makes the SKS reconciler here a little more robust and relies on the correct contracts.
/assign @nak3
=> Use SKS' PrivateServiceName field rather than generate it

third_party/istio-stable/extra/istio-mesh.yaml, third_party/istio-stable/generate-manifests.sh, third_party/istio-stable/istio-ci-mesh/istio.yaml, third_party/istio-stable/istio-kind-mesh/istio.yaml
mTLS was disabled in https://github.com/knative-sandbox/net-istio/pull/517  But this is causing confusion downstream in `serving` since we didn't realize the change had occurred.
Going forward I think we should have consistency with our `istio-*` yamls and perform any specific overrides in `serving` 
Related: https://github.com/knative-sandbox/net-istio/issues/503
=> [istio-stable] renable global mTLS when in mesh mode

pkg/reconciler/ingress/resources/virtual_service.go, pkg/reconciler/ingress/resources/virtual_service_test.go
For  https://github.com/knative-sandbox/net-istio/issues/630
This reduces the number of routes generated for a single KService by 1/3
in most cases. I profiled this on the Istio control plane side and saw a
corresponding ~50% drop in CPU usage to compute the routes.
/kind performance
```release-note
Optimized generated routes to minimize Envoy configuration size
```
**Docs**
```docs
```
=> Deduplicate host matches to avoid excessive matches

config/203-local-gateway.yaml
This was added to Istio in https://github.com/istio/istio/pull/33021. It
will likely be available in 1.9.next and 1.10.next, but if the label is
present with an older Istio version its not a problem - it will just not
have any impact.
What this does is avoid the ambiguities we currently have with the
Gateway service selection. Currently, if the local gateway is created
before the external gateway, we will be broken because the "port 80"
Gateway will match the local gateway and get translated to port 8081,
when it should be translated to port 8080 of the external gateway.
What this label does is tell Istio that the local gateway service is not
eligible for this port translation; as a result, Gateways on port 80
will never be mapped to port 8081. Instead, we expect that port 8081
will be …
=> Set "disable-gateway-port-translation" label on local gateway Service

pkg/reconciler/ingress/resources/gateway.go
As per title, this patch removes unused function.
It was not called anywhere since https://github.com/knative-sandbox/net-istio/commit/4369c9caa776f5b417d57d897c10a402f6cdd1bb .
=> Remove unused function ServiceNamespaceFromURL

pkg/reconciler/ingress/resources/gateway.go
The `hosts` variable is not used in any places.
=> delete the unused code

pkg/reconciler/ingress/ingress.go, pkg/reconciler/ingress/resources/gateway.go, pkg/reconciler/ingress/resources/gateway_test.go
For the wildcard Gateway case, a VirtualService ties to both the wildcard Gateway as well as the default global Gateway. (see https://github.com/knative-sandbox/net-istio/blob/main/pkg/reconciler/ingress/ingress.go#L115)
When auto TLS is enabled, the HTTP server of the global Gateway is reconciled to desired shape. So there is no need to add the desired HTTP server to the wildcard Gateway.
/cc @nak3
=> No need to create HTTP server for wildcard gateway

third_party/istio-latest/generate-manifests.sh, third_party/istio-latest/istio-ci-mesh/istio.yaml, third_party/istio-latest/istio-ci-no-mesh/istio.yaml, third_party/istio-latest/istio-kind-mesh/istio.yaml, third_party/istio-latest/istio-kind-no-mesh/istio.yaml, third_party/istio-stable/generate-manifests.sh, third_party/istio-stable/istio-ci-mesh/istio.yaml, third_party/istio-stable/istio-ci-no-mesh/istio.yaml, third_party/istio-stable/istio-kind-mesh/istio.yaml, third_party/istio-stable/istio-kind-no-mesh/istio.yaml
As per title, this patch updates Istio versions.
__BEFORE__
latest: 1.9.3
stable: 1.9.1
__AFTER__
latest: 1.10.1
stable: 1.9.5
Fix https://github.com/knative-sandbox/net-istio/issues/631 https://github.com/knative-sandbox/net-istio/issues/667 https://github.com/knative-sandbox/net-istio/issues/667
=> Update Istio latest to 1.10.1 stable to 1.9.5

third_party/istio-head/istio-ci-mesh.yaml, third_party/istio-head/istio-ci-no-mesh.yaml, third_party/istio-head/istio-kind-mesh.yaml, third_party/istio-head/istio-kind-no-mesh.yaml, third_party/istio-latest/istio-ci-mesh.yaml, third_party/istio-latest/istio-ci-mesh/istio.yaml, third_party/istio-latest/istio-ci-no-mesh.yaml, third_party/istio-latest/istio-ci-no-mesh/istio.yaml, third_party/istio-latest/istio-kind-mesh.yaml, third_party/istio-latest/istio-kind-mesh/istio.yaml, third_party/istio-latest/istio-kind-no-mesh.yaml, third_party/istio-latest/istio-kind-no-mesh/istio.yaml, third_party/istio-stable/istio-ci-mesh.yaml, third_party/istio-stable/istio-ci-mesh/istio.yaml, third_party/istio-stable/istio-ci-no-mesh.yaml, third_party/istio-stable/istio-ci-no-mesh/istio.yaml, third_party/istio-stable/istio-kind-mesh.yaml, third_party/istio-stable/istio-kind-mesh/istio.yaml, third_party/istio-stable/istio-kind-no-mesh.yaml, third_party/istio-stable/istio-kind-no-mesh/istio.yaml
Istio upstream drops `TERMINATION_DRAIN_DURATION_SECONDS` since 1.10
https://github.com/istio/istio/commit/f6502508b04c38f9678c300821dd54e439b832ed.
/kind cleanup
=> Use terminationDrainDuration in MeshConfig.defaultConfig

third_party/istio-latest/generate-manifests.sh, third_party/istio-latest/istio-ci-mesh/istio.yaml, third_party/istio-latest/istio-ci-no-mesh/istio.yaml, third_party/istio-latest/istio-kind-mesh/istio.yaml, third_party/istio-latest/istio-kind-no-mesh/istio.yaml, third_party/istio-stable/generate-manifests.sh, third_party/istio-stable/istio-ci-mesh/istio.yaml, third_party/istio-stable/istio-ci-no-mesh/istio.yaml, third_party/istio-stable/istio-kind-mesh/istio.yaml, third_party/istio-stable/istio-kind-no-mesh/istio.yaml
- bump stable to 1.9.6
- bump latest patch to 1.10.2
=> bump patches

pkg/reconciler/ingress/ingress_test.go
This patch fixes the lint error:
https://github.com/knative-sandbox/net-istio/runs/3375284605?check_suite_focus=true
It is same fix with https://github.com/knative/serving/commit/d9328556ad0944de268a975d32ed9883a727e26b
/cc @ZhiminXiang @tcnghia @markusthoemmes
=> Fix deprecation lint error

test/e2e-tests.sh
This reverts commit 2c2f2de479e7534a2bba6b04aeecb3efb04557bc.
It seems test became stable. [Contour uses 1.21](https://testgrid.k8s.io/r/knative-own-testgrid/net-contour#continuous) but it is all green recently.
=> Revert "Use GKE 1.20 (#781)"

config/200-clusterrole.yaml, config/202-gateway.yaml, config/203-local-gateway.yaml, config/400-config-istio.yaml, config/400-webhook-peer-authentication.yaml, config/500-controller.yaml, config/500-webhook-deployment.yaml, config/500-webhook-secret.yaml, config/500-webhook-service.yaml, config/600-mutating-webhook.yaml, config/600-validating-webhook.yaml, hack/release.sh, pkg/reconciler/ingress/config/testdata/config-istio.yaml, pkg/reconciler/ingress/config/testdata/config-network.yaml, test/config/200-service-account.yaml, test/config/chaosduck.yaml, third_party/istio-head/extra/config-istio-mesh.yaml, third_party/istio-head/extra/config-istio.yaml, third_party/istio-head/istio-ci-mesh/config-istio.yaml, third_party/istio-head/istio-ci-no-mesh/config-istio.yaml, third_party/istio-head/istio-kind-mesh/config-istio.yaml, third_party/istio-head/istio-kind-no-mesh/config-istio.yaml, third_party/istio-latest/extra/config-istio-mesh.yaml, third_party/istio-latest/extra/config-istio.yaml, third_party/istio-latest/istio-ci-mesh/config-istio.yaml, third_party/istio-latest/istio-ci-no-mesh/config-istio.yaml, third_party/istio-latest/istio-kind-mesh/config-istio.yaml, third_party/istio-latest/istio-kind-no-mesh/config-istio.yaml
Adds Kubernetes recommended labels to networking as discussed in https://github.com/knative/networking/issues/552
Note that changes to the labels in `vendor/knative.dev/networking` should be handled by the automation once https://github.com/knative/networking/pull/555 merges. 
=> Add k8s recommended labels

config/400-webhook-peer-authentication.yaml
Due to [Support for integer keys](https://github.com/kubernetes-sigs/kustomize/issues/3446) bug, integer keys can not be used with kustomize.
Ideally, it should be solved on kustomize side, but the solution requires much more work and I think making keys string will not harm anybody. 
PeerAuthentications manifests' spec.portLevelMtls keys are converted to string type from integer.
Fixes #840
=> Use for string keys instead of integer keys on PeerAuthentications.

.github/workflows/kind-e2e.yaml
As k8s min version was bumped to 1.21 by https://github.com/knative/pkg/pull/2397, this patch bumps k8s version in kind.
=> Bump k8s version to 1.23.0 in kind

config/600-validating-webhook.yaml
As part of https://github.com/knative/serving/issues/12215 we're planning to transition from the `serving.knative.dev/release` label to the recommended `app.kubernetes.io` label in Serving. This PR updates the net-certmanager validating webhook to use the new label.
```release-note
Switches selectors for Knative resources to use the recommended `app.kubernetes.io` labels
```
/assign @dprotaso
=> Updates webhook to use app.kubernetes.io selector label

config/600-validating-webhook.yaml
When we install net-istio with serving, multiple validating
webhooks are registered.
Previously, the webhooks were configured with just namespace
selectors that are identical. Thus when config-istio is updated,
the serving webhook is invoked (which is a noop) and vice-versa
for any serving config maps.
To avoid this, this PR updates the validating webhook to use an
objectSelector and includes an extra label (`component:net-istio`)
to further distinguish net-istio resources from serving resources.
/kind cleanup
Part of https://github.com/knative/serving/issues/12594
```release-note
Updates net-istio validating webhook to use an objectSelector to reduce unnecessary webhook invocations
```
**Docs**
```docs
```
=> Updates val webhook selector to reduce invocations

config/200-clusterrole.yaml, config/202-gateway.yaml, config/203-local-gateway.yaml, config/400-config-istio.yaml, config/400-webhook-peer-authentication.yaml, config/500-controller.yaml, config/500-webhook-deployment.yaml, config/500-webhook-secret.yaml, config/500-webhook-service.yaml, config/600-mutating-webhook.yaml, config/600-validating-webhook.yaml, hack/release.sh, pkg/reconciler/ingress/config/testdata/config-istio.yaml, pkg/reconciler/ingress/config/testdata/config-network.yaml, test/config/200-service-account.yaml, test/config/chaosduck.yaml
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
Previously agreed these labels would be dropped in release v1.4
Follow on to #804 , #861 
See https://github.com/knative/serving/issues/12215 for more details.
```release-note
`serving.knative.dev/release` labels, deprecated in v1.3, have been removed. Please switch over to using `app.kubernetes.io/name: knative-serving` and `app.kuberentes.io/version: devel`.
```
=> Removing deprecated serving.knative.dev/release label

config/400-config-istio.yaml, pkg/reconciler/ingress/config/istio.go, pkg/reconciler/ingress/config/istio_test.go, pkg/reconciler/ingress/config/testdata/config-istio.yaml
As per https://github.com/knative/serving/issues/11523, this patch removes `local-gateway.mesh: "mesh"`.
Please note that it does not remove `local-gateway.<GATEWAY>: <GATEWAY_SVC>` is still availble.
This patch removes only `mesh` which is a special configuration.
```release-note
`local-gateway.mesh: "mesh"` option was dropped.
```
/cc @ZhiminXiang @carlisia
=> Remove `local-gateway.mesh: "mesh"` option

.github/workflows/kind-e2e.yaml
This patch bumps kind version 0.12.0 for k8s 1.23.
Since an issue https://github.com/knative/networking/issues/660 exists before,
we didn't update the version but it could be fixed by
dropping `apiVersion: kubeadm.k8s.io/v1beta2` from `kubeadmConfigPatches`.
=> Bump kind version to 0.12.0 for k8s 1.23

pkg/reconciler/ingress/config/store.go, pkg/reconciler/ingress/config/store_test.go, pkg/reconciler/ingress/controller.go, pkg/reconciler/ingress/ingress.go, pkg/reconciler/ingress/ingress_test.go, pkg/reconciler/ingress/lister.go, pkg/reconciler/ingress/resources/gateway_test.go, pkg/reconciler/serverlessservice/resources/virtualservice.go, pkg/reconciler/serverlessservice/serverlessservice_test.go
- As per title. golangci lint is broken due to latest net api deprecation.
=> Fix net deprecations

.github/workflows/kind-e2e.yaml
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
Since we will probably be supporting Kubernetes v1.24 in the next release, and kind v0.13.0+ is required to run Kubernetes v1.24.0+ images, let's go ahead and bump the versions now, so we have a chance to work out any issues before the next release.
=> bump kind and k8s versions for kind-e2e test

.github/workflows/kind-e2e.yaml, third_party/istio-latest/istio-ci-mesh/istio.yaml, third_party/istio-latest/istio-ci-no-mesh/istio.yaml, third_party/istio-latest/istio-kind-no-mesh/istio.yaml, third_party/library.sh
Due to an issue in `istioctl manifest generates`, the manifest does not  produce `policy/v1`.
This patch adds the workaround which replaces the version by sed in script.
Fix https://github.com/knative-sandbox/net-istio/issues/993
=> Add workaround for k8s 1.25

cmd/webhook/main.go, config/500-webhook-deployment.yaml, config/500-webhook-service.yaml
Make the webhook port number configurable
Previously the webhook listened on a fixed port, 8443, which can clash
with other services when the webhook is run on the host network in
Kubernetes, which is required when using some CNI implementations,
notably Calico on EKS [1].
Enable configuration of the webhook listen port through the environment
variable WEBHOOK_PORT by using the existing API from the KNative SDK.
[1] https://projectcalico.docs.tigera.io/getting-started/kubernetes/managed-public-cloud/eks#install-eks-with-calico-networking
Signed-off-by: Steve Larkin <steve.larkin@gmail.com>
=> Make the webhook port number configurable

pkg/reconciler/ingress/resources/gateway.go, pkg/reconciler/ingress/resources/gateway_test.go
I have Knative and Istio together with net-istio running, and I created a domain mapping with a long name. Knative Serving turned this into a KIngress with name `areallyverylongdomainnamethatexcd8923dee789a086a0ac46d3046cbec7`. Based on that, Net-Istio tried to create a gateway name `areallyverylongdomainnamethatexcd8923dee789a086a0ac46d3046cbec7-3797421420` which is [rejected by Istio's validating webhook](https://github.com/istio/istio/blob/1.16.1/pkg/config/validation/validation.go#L463-L465):
```
Message: admission webhook "validation.istio.io" denied the request: configuration is invalid: invalid gateway name: "areallyverylongdomainnamethatexcd8923dee789a086a0ac46d3046cbec7-3797421420"
```
I am changing the logic to shorten the prefix as much as needed.
/kind bug …
=> Ensure that a Gateway name does not exceed 63 length

pkg/reconciler/accessor/core/secret.go, pkg/reconciler/ingress/ingress_test.go, pkg/reconciler/ingress/resources/secret.go, pkg/reconciler/ingress/resources/secret_test.go
When recently doing https://github.com/knative-sandbox/net-istio/pull/1043, I was already surprised that a wildcard certificate copy in the Istio system namespace is NOT getting any labels to track back the original secret.
I now verified that this is indeed causing issues:
1. An update of the original secret is not propagated to the copy.
2. The secret copy is never deleted even if it is not needed anymore.
I am therefore setting the same labels and annotation on a wildcard secret in this PR. The main change is in pkg/reconciler/ingress/resources/secret.go.
The purpose of the change in pkg/reconciler/accessor/core/secret.go is to fix all existing secret copies' labels. The test case change in pkg/reconciler/ingress/ingress_test.go is related to this given the missing label is now also …
=> Ensure wildcard certificate secrets can also track back their source secret

go.mod
See: https://github.com/knative/serving/issues/13747
=> [release-1.8] trigger to build release with go1.19.6 

third_party/istio-latest/generate-manifests.sh, third_party/istio-latest/istio-ci-mesh/istio.yaml, third_party/istio-latest/istio-ci-no-mesh/istio.yaml, third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Fixes CVEs
https://istio.io/latest/news/releases/1.16.x/announcing-1.16.3/
=> [release-1.9] bump istio to v1.16.3

test/e2e-tests.sh
Forgot to undo this in https://github.com/knative-sandbox/net-istio/pull/1078
=> disable telemetry in e2e tests

cmd/webhook/main.go, pkg/defaults/deployment_defaults.go, pkg/reconciler/accessor/core/secret.go, pkg/reconciler/ingress/ingress.go, pkg/reconciler/ingress/ingress_test.go, pkg/reconciler/ingress/lister_test.go, pkg/reconciler/ingress/resources/virtual_service.go, pkg/reconciler/ingress/resources/virtual_service_test.go, test/e2e/clients.go, test/e2e/e2e.go
- :broom: fixing golangci-lint issues
- :broom: removing unused parameters or setting `_` where necessary because of interfaces
/kind cleanup
=> Fixing golangci-lint issues

.github/workflows/kind-e2e.yaml
This patch bumps k8s version on CI and changes to use `chainguard-dev/actions/setup-kind@main` for setup.
=> Bump k8s version on github action

pkg/reconciler/ingress/ingress_test.go, pkg/reconciler/ingress/resources/gateway_test.go, pkg/reconciler/ingress/resources/secret.go, pkg/reconciler/ingress/resources/secret_test.go, pkg/reconciler/ingress/resources/util.go
This pull request changes the implementation of isWildcardSecret to check all host names in the certificate instead of only the first one. We often use certificates with two host names, something like `*.example.com` and `example.com`. If the host names are in that order, then the function correctly returned `true`. If the first host name is not wildcard, then it returned false. Subsequently, no wildcard gateway was created.
/kind bug
```release-note
Certificates with multiple hosts where a non-first-entry is a wildcard host are now correctly detected as wildcard secrets
```
=> Check all host names of a certificate in isWildcardSecret

.github/workflows/kind-e2e.yaml
- Update version in kind-e2e.yaml
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Bump kind version

test/e2e-tests.sh
This test is very flakey and hindering contributions to this repo - we need fix this but in the meantime let's disable it
See: https://github.com/knative-sandbox/net-istio/issues/938
=> Disable update test

.github/workflows/kind-e2e.yaml, test/config/100-serving-namespace.yaml, test/config/100-test-namespace.yaml, third_party/istio-latest/istio-ci-ambient.yaml, third_party/istio-latest/istio-ci-ambient/istio.yaml, third_party/istio-latest/istio-kind-ambient.yaml, third_party/istio-latest/istio-kind-ambient/istio.yaml, third_party/library.sh
As per title, this patch adds ambient profile under `third_party` and github action.
Fix https://github.com/knative-sandbox/net-istio/issues/1103
=> Add ambient profile

third_party/istio-latest/istio-kind-ambient.yaml, third_party/istio-latest/istio-kind-ambient/istio.yaml, third_party/istio-latest/istio-kind-no-mesh.yaml, third_party/istio-latest/istio-kind-no-mesh/istio.yaml
As per title, this patch drops NodePort from kind manifests which is used by github action.
=> Drop NodePort from kind manifests

config/400-webhook-peer-authentication.yaml
As per title, it was removed since https://github.com/knative/serving/commit/fc166ac8b459a73116ca5535e168aba2d97a2626
=> Drop PeerAuthentication for domainmapping-webhook

pkg/reconciler/ingress/ingress.go, pkg/reconciler/ingress/ingress_test.go, pkg/reconciler/ingress/lister.go, pkg/reconciler/ingress/resources/gateway.go, pkg/reconciler/ingress/resources/virtual_service.go, pkg/reconciler/ingress/resources/virtual_service_test.go
- :broom: Migrate `sets.String` to `sets.Set[string]` when possible, `sets.String` being deprecated
- Not every place could have been changed, some dependencies (internal to knative, external to this repo) are still using `sets.String`
/kind cleanup
This chnages is motivated by the linter complaining about that
=> chore: Migrate to sets.Set[string] when possible

.github/workflows/kind-e2e.yaml
- Bumps golang to version 1.21
- Bumps kind version range from 1.26-1.28
Fixes #1167
=> Bump golang and kind version

third_party/istio-latest/generate-manifests.sh, third_party/istio-latest/istio-ci-ambient/istio.yaml, third_party/istio-latest/istio-ci-mesh/istio.yaml, third_party/istio-latest/istio-ci-no-mesh/istio.yaml, third_party/istio-latest/istio-kind-ambient/istio.yaml, third_party/istio-latest/istio-kind-no-mesh/istio.yaml
- Bump istio manifests to v1.19.0
- We cannot bump the go-deps yet, see https://github.com/knative-extensions/net-istio/issues/1168#issuecomment-1731035128
Partially #1168 
Fixes #1177
/assign @dprotaso 
/assign @nak3
=> Bump istio manifests to v1.19.0

third_party/istio-latest/generate-manifests.sh, third_party/istio-latest/istio-ci-ambient/istio.yaml, third_party/istio-latest/istio-ci-mesh/istio.yaml, third_party/istio-latest/istio-ci-no-mesh/istio.yaml, third_party/istio-latest/istio-kind-ambient/istio.yaml, third_party/istio-latest/istio-kind-no-mesh/istio.yaml
This patch mumps istio manifest version to 1.19.3 which fixes [the security vulnerabilities.](https://istio.io/latest/news/releases/1.19.x/announcing-1.19.3/)
=> Bump Istio to 1.19.3

third_party/library.sh
`curl` is present by default on most systems - i ran the generate script and had to install wget
Also we use a lot of curl in serving so we can standardize on it
=> Use curl instead of wget

.github/workflows/kind-e2e.yaml
Shortens
`KinD e2e tests / e2e tests (v1.27.x, ./test/conformance, latest, system-internal-tls, ambient)`
to
`e2e / test (v1.27.x, ./test/conformance, latest, system-internal-tls, ambient) `
=> Shorten kind/e2e GitHub Action Names

.github/workflows/kind-e2e.yaml
- Drop testing on k8s v1.26
Fixes #1217
/assign @dprotaso 
/assign @nak3
=> Drop testing on k8s v1.26

pkg/reconciler/ingress/ingress.go, pkg/reconciler/ingress/resources/gateway.go, pkg/reconciler/ingress/resources/gateway_test.go, pkg/reconciler/ingress/resources/secret.go, pkg/reconciler/ingress/resources/secret_test.go
Although net-istio does not support `cluster-local-domain-tls`, enabling the feature will create additional entries in `IngressTLS`. As net-istio only expects entries for `IngressVisibilityExternalIP` visibilities, this PR filters them out to keep the existing behaviour.
- Filter IngressTLS for visibility IngressVisibilityExternalIP
Partially https://github.com/knative/serving/issues/14624
/assign @dprotaso 
/assign @nak3 
=> Filter IngressTLS for visibility IngressVisibilityExternalIP 

config/700-istio-knative-certificate.yaml, test/e2e-common.sh
- Followup for https://github.com/knative-extensions/net-istio/pull/1221
- Removing the file results in the `KnativeCertificate` not being in the release manifest: https://github.com/knative/serving/pull/14610/commits/a42001549c5dbe9a57c2ebd6ecc30db467408629#diff-845c4618eefc690238aaab455d8f1b79ffd5c30eec4c2f5b50da9b57017b39a8L588
- Use ko label filter instead of removing KnativeCertificate yaml
=> Use ko label filter instead of removing KnativeCertificate yaml

config/203-local-gateway.yaml, pkg/reconciler/ingress/ingress.go, pkg/reconciler/ingress/ingress_test.go, pkg/reconciler/ingress/resources/gateway.go, pkg/reconciler/ingress/resources/gateway_test.go, pkg/reconciler/ingress/resources/secret.go, pkg/reconciler/ingress/resources/secret_test.go
- Add cluster-local https servers when `cluster-local-domain-tls` is enabled and a KSVC exists
- Uses SNI to host multiple certificates for all cluster-local domain Knative Services
Fixes https://github.com/knative/serving/issues/14374
```release-note
net-istio now hosts an additional gateway with TLS for each Knative Service when `cluster-local-domain-tls` is enabled. Note: this is an experimental alpha-feature.
```
**Docs**
Will be done once the features is complete
=> Host cluster-local-domain-tls on cluster-local gateway with SNI

go.mod, pkg/reconciler/ingress/config/istio.go, pkg/reconciler/ingress/config/istio_test.go
- Introduce new configuration format
Fixes #1247 
```release-note
A new configuration format has been introduced. Old format is still supported. See https://docs.google.com/document/d/12X1-9nhjAhpf-Wlt3RbdoMbvx31zFBva/edit for more details
```
**Docs**
```docs
```
=> feat: New istio config format

.github/workflows/kind-e2e.yaml
- drop k8s v1.27 from kind testing
PS: Bump of client libraries will happen in https://github.com/knative/pkg/issues/2958
=> drop k8s 1.27 from kind testing

test/e2e-tests.sh
- specify cluster version to 1.28 in e2e test scripts
Fixes #1269
=> bump e2e cluster version to 1.28

config/700-istio-knative-certificate.yaml
- Add missing common labels on kcert
- Without these, the operator does not properly select these YAMLs
/assign @skonto 
/cherry-pick release-1.14
=> Add missing common labels on kcert

pkg/reconciler/ingress/resources/gateway.go
Pull request [Support Gateway Selection using Ingress Labels #1250](https://github.com/knative-extensions/net-istio/pull/1250) removed the call to `GetIngressGatewaySvcNameNamespaces` but left the now useless error check.
/kind cleanup
=> Remove useless if

pkg/reconciler/ingress/resources/virtual_service.go, pkg/reconciler/ingress/resources/virtual_service_test.go
- 🐞  Properly propagate route header matching rules to the virtual service
/kind <kind>
Fixes: https://github.com/knative-extensions/net-istio/issues/847 https://github.com/knative-extensions/net-istio/issues/1313
```release-note
Properly propagate route header matching rules to the virtual service
```
=> preserve appropriate header matches when creating the virtualservice

config/500-controller.yaml
Partially https://github.com/knative/serving/issues/15521
* Use istio.sidecar.inject label instead of annotation
=> Use istio.sidecar.inject label instead of annotation

.github/workflows/kind-e2e.yaml
- #1387 tests fail. Chainguard dropped support for 1.28.  We can always merge now and revert in #1388 later., or go directly for #1388.
=> Pin Chainguard version

.github/workflows/kind-e2e.yaml, test/e2e-tests.sh
- Similar to https://github.com/knative-extensions/net-istio/pull/1270 and https://github.com/knative-extensions/net-istio/pull/1170
- We need it for 1.17 and now tests on PRs fail due to the fact that Chainguard action dropped support 1.28.
=> Bump Kind and k8s version

test/e2e-common.sh
There were conflicting `--platform` flags in the nightly release
=> fix nightly build

hack/update-codegen.sh, test/e2e-tests.sh
- [release-1.16] Move codegen script to new kube_codegen.sh
PTAL, this is a usual codegen refactor to make sure `release-1.16` codegen scripts work with kube_codegen.sh stuff. Later release branch and main is OK. 
/cc @skonto @dprotaso
=> [release-1.16] Move codegen script to new kube_codegen.sh

.github/workflows/kind-e2e.yaml, .golangci.yaml, pkg/reconciler/ingress/resources/gateway.go, pkg/reconciler/testing/factory.go
- bump kind e2e testing to v1.32 & 1.33
- adjust error message in linter warning
- linter fixes
=> adjust linter and ci k8s version
